name: Release

on:
  push:
    tags:
      - "*"

env:
  REGISTRY: ghcr.io

permissions:
  contents: write
  packages: write
  attestations: write

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker buildx build -t ghcr.io/bjarnerentz/central-cyclone:latest -t ghcr.io/bjarnerentz/central-cyclone:${{ github.ref_name }} --push .
    
    - name: Create release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        tag="${GITHUB_REF#refs/tags/}"

        gh release create "$tag" \
          --title="$tag" \
          --draft \
          --generate-notes \
          main.js manifest.json styles.css
